### ISSUE TITLE
Improve error message when ID is missing

### ISSUE THREAD

**Issue by r-diamond** [copyblogger/genesis-simple-sidebars#11]
I created a Dynamic Sidebar, and since a) I'm used to post slugs auto-generating and b) it's been a while since I used it, I neglected to use the ID.

That led to this error screen:

![image](https://cloud.githubusercontent.com/assets/3864662/7961651/4536019a-09df-11e5-9fc0-1a702f0b39ec.png)

I then had to use the back button in my browser and add the ID.

Is there any way to do an on-screen error like we do when processing payments, where the missing or incorrect box is highlighted?

(Tested this in Rainmaker, on this site: http://rebecca-rainmaker.pre-nyc2-01.rmkr.net/ Mac/Chrome)

Tagging @nathanrice but if it should go to someone else, please re-assign :D

**Comment by billerickson** [comment]
A better option would be to make it work just as you expected it to - if no slug is provided, auto-generate it based on the name. Just pass the name through sanitize_title()

**Comment by dreamwhisper** [comment]
A better option would be to make it work just as you expected it to - if no slug is provided, auto-generate it based on the name. Just pass the name through sanitize_title()

+ 1 for that

**Comment by nathanrice** [comment]
f96e67d
4e5bfa7

**Comment by dreamwhisper** [comment]
Every once in awhile, I still get this message, but haven't yet sorted the steps to replicate. IDs are definitely auto generating. 

When it happens, I have to refresh the screen, then I can add a sidebar with the same name I was trying.

**Comment by nickcernis** [comment]
I tried to reproduce this and so far only see “choose a valid Name” for '' (no value) or 0 (equates to empty).

We could try `'' === $args['name']` instead of `empty( $args['name'] )`?

~~~php
if ( '' === $args['name'] ) {
	wp_die( $this->error( 1 ) );
	exit;
}
~~~

**Comment by dreamwhisper** [comment]
@jaygidwitz could you give this a shot and just make sure it is working for you on a WP Install (develop branch - https://github.com/copyblogger/genesis-simple-sidebars/archive/develop.zip)? 

I'm not getting this in my testing today so it could be my rapid fire testing Friday/Saturday. If it is good for everyone else, I'm cool with it.

**Comment by jaygidwitz** [comment]
Okay so, little problem I think:

I made a sidebar named `Sidebar`. (That's my creative side.)

I left the id blank. So an id of `gss-sidebar-1` was generated.

Now whenever I add a widget to this sidebar it also is added to the primary sidebar with and id of `sidebar`

<img width="770" alt="screenshot 2017-03-06 14 12 13" src="https://cloud.githubusercontent.com/assets/3248407/23633763/e49a0c90-027b-11e7-85c1-1781cc9343a5.png">

Noting that I was not able to replicate this with other sidebars subsequently.

Testing if this a prexisting bug in Production:

- I cannot replicate exactly b/c when I do this with the production plugin I get the error that this issue is meant to solve.
- When I create a new sidebar with gss 2.0.4 & name the sidebar `Sidebar` and give it an id of `sidebar` even though there is an existing sidebar with that name, then the gss sidebar replaces that one.
- So this maybe somewhat preexisting.

I was able to replicate this again with the develop plugin but following the above instructions on a different wp install.

- Also noting I was able to replicate @nickcernis's issue in the method he described.

@dreamwhisper I wasn't able to replicate your error other than using nick's methods.

I also don't know if my error is more of an edge case and if you would simply like a new issue for this, or if it's too much of an edge case and we don't need an issue.

**Comment by nathanrice** [comment]
I'm curious if creating a sidebar manually with the same specs gives the same result.

Name => Sidebar
ID => gss-sidebar-1

**Comment by jaygidwitz** [comment]
Yes, testing it on a third site, it does.

<img width="757" alt="screenshot 2017-03-06 15 23 56" src="https://cloud.githubusercontent.com/assets/3248407/23634787/fa4ecbde-0280-11e7-8834-96cc71401f4e.png">

**Comment by nathanrice** [comment]
OK, let's get this into another issue. It might not even be fixable. Seems like WordPress basically ignores the ID and is using the Title in some instances. I'll have to investigate. But this shouldn't hold back a release, IMO.

**Comment by dreamwhisper** [comment]
:thumbsup:
