### ISSUE TITLE
Can activate if Genesis not active

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-sidebars#19]
Same as https://github.com/copyblogger/genesis-simple-hooks/issues/11.

(develop branch e5c3b52 )

**Comment by nathanrice** [comment]
Fixed. What say you, @nickcernis ?

**Comment by dreamwhisper** [comment]
@nathanrice I'd like to open the Genesis download link in a new window. Otherwise, we take them out of their admin to log in at my.studiopress.com. Probably nitpicky, but that download link won't always be Genesis 2.4.2, right? So, should only Genesis be linked?

I think that `Please upgrade or deactivate this plugin.` sounds like they need to upgrade the plugin.

Does it make more sense to do it this way?

![genesis](https://cloud.githubusercontent.com/assets/1271053/23619525/ed2eaec0-0261-11e7-9e25-681edda3d80a.png)

**Comment by nathanrice** [comment]
Yeah, we can open in a new window. And the download link will always be the main Genesis download link. That never changes. The only think that changes is what file we attach to that download link.

Let me play with the wording a little.

**Comment by nathanrice** [comment]
e5afd4f9ef8100bdeb297b88e8b3f3304e8114ec
491a2b74fc69e585346b1cc5b00acc587952bb83

**Comment by dreamwhisper** [comment]
@nathanrice Simple Sidebars says Simple Hooks: https://github.com/copyblogger/genesis-simple-sidebars/commit/491a2b74fc69e585346b1cc5b00acc587952bb83#diff-da7dc05e9c501b38610a73456329ff2bR97

**Comment by nathanrice** [comment]
991b354

**Comment by dreamwhisper** [comment]
Cool that's fixed :)

Just bringing up the link location again. Since the link will not always be linking to the version displayed in the message, I think it is a better UX and more accessible to link in `Please install and activate the latest version of Genesis to use this plugin.`

For example, it currently says `Genesis Simple Hooks requires WordPress 4.7.2 and Genesis 2.4.2, or greater.` and Genesis 2.4.2 is linked. However, we could be linking to Genesis 2.5.

**Comment by nathanrice** [comment]
Good point. Done.

**Comment by dreamwhisper** [comment]
Thanks @nathanrice!

Confirmed on an old version of G that the message says please upgrade.

A couple other things:
- https://github.com/copyblogger/genesis-simple-sidebars/blob/develop/genesis-simple-sidebars.php#L89 for Simple Sidebars should be 2.1.0.
- https://github.com/copyblogger/genesis-simple-sidebars/blob/develop/readme.txt#L5-L6 - if it does require WP 4.7.2, we need to change the requires and tested up to. (probably something you would do later, but just don't want to miss it.)

Otherwise, calling this good.

**Comment by nickcernis** [comment]
+1 Looks good save for @dreamwhisper's suggestions.

**Comment by nathanrice** [comment]
@dreamwhisper fixed your first suggestion, and will fix the other when it's time to tag and release.
