### ISSUE TITLE
Sidebar for Home

### ISSUE THREAD

**Issue by GaryJones** [copyblogger/genesis-simple-sidebars#3]
1.  Use GSS to create a sidebar called Home with a slug of `home`.
2. Create a Page with a title of Home and a slug of `home`.
3. Ensure it is set to show at least the primary sidebar.
4. Assign Home as the Primary sidebar.
5. Assign the page as a static front page (Settings->Reading).
6. Add a widget to Home.
7. Visit the page on the front-end.

For me, I just get an empty `<aside ...></aside>`.

I'm not sure if this is something special to do with the `home` slug of the widget area, or something special about the page being the static front page, but creating the sidebar with the name of `home-page` instead works as intended.

**Comment by nickcernis** [comment]
Noting I can no longer reproduce this with Simple Sidebars 2.1.0, WP 4.8, Genesis 2.5.2 and Genesis Sample 2.3.0. I see the expected Home sidebar instead of a blank `<aside>`.

<img width="371" alt="genesis_-_simple_sidebars_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/28667972-c3507bea-72c5-11e7-8239-fa28b6a905f1.png">
<img width="612" alt="reading_settings_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/28667902-6bca2c0e-72c5-11e7-8851-082e641f4416.png">
<img width="301" alt="edit_page_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/28667942-9d04443a-72c5-11e7-860d-3e9ed0025525.png">
<img width="435" alt="widgets_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/28668017-e9130546-72c5-11e7-8f50-53ee361c0f87.png">
<img width="983" alt="wp_test_ _just_another_wordpress_site" src="https://user-images.githubusercontent.com/647669/28667927-879c27f2-72c5-11e7-8947-4dcdfafd411c.png">

**Comment by GaryJones** [comment]
Fine to close now then - can always be re-opened if needed.
